apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ curator_configmap_config.name }}
  namespace: {{ curator_configmap_config.namespace }}
data:
  curator.yml: |-
    client:
      hosts:
        - {{ elasticsearch_hostname }}
      port: {{ elasticsearch_port }}
      url_prefix:
      use_ssl: False
      certificate:
      client_cert:
      client_key:
      ssl_no_validate: False
      http_auth:
      timeout: 30
      master_only: False

    logging:
      loglevel: INFO
      logfile: /var/log/curator/curator.log
      logformat: default
      blacklist: ['elasticsearch', 'urllib3']
