apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ curator_configmap_pipeline.name }}
  namespace: {{ curator_configmap_pipeline.namespace }}
data:
  pipeline.yml: |-
    actions:
    {% for tasks in curator_actions %}
      {{ tasks.order }}:
        action: {{ tasks.action }}
        description: "{{ tasks.description }}"
        options:
          ignore_empty_list: True
          continue_if_exception: True
        filters:
    {% for filter in tasks.filters %}
          -
    {% for key, value in filter.iteritems() %}
            {{ key }}: "{{ value }}"
    {% endfor %}
    {% endfor %}
    {% endfor %}
